version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3001" # Host Port 3000 -> Container Port 3001
    environment:
      - MONGO_URI=mongodb://mongo:27017/igdanalistas
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      # - .:/app  <-- Removed to allow Docker image build artifacts (dist folder) to be visible
      # - /app/node_modules <-- Removed as we are not mounting source code


  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    # Optional: ports mapping if you want to access Mongo from host tools
    # ports:
    #   - "27017:27017"

volumes:
  mongo-data:
